all: \
  Debug/stm32.elf\

-include Debug/freertos.d
Debug/freertos.o:Core/Src/freertos.c
	C:/ARMToolchain/bin/arm-none-eabi-gcc -c -DDEBUG -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Core/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Device/ST/STM32F4xx/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F Core/Src/freertos.c -MD -MF Debug/freertos.d -fno-diagnostics-show-caret -o Debug/freertos.o -Os -g3 -ffunction-sections -fdata-sections -Wall -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mlittle-endian

-include Debug/LCD.d
Debug/LCD.o:Core/Src/LCD.c
	C:/ARMToolchain/bin/arm-none-eabi-gcc -c -DDEBUG -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Core/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Device/ST/STM32F4xx/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F Core/Src/LCD.c -MD -MF Debug/LCD.d -fno-diagnostics-show-caret -o Debug/LCD.o -Os -g3 -ffunction-sections -fdata-sections -Wall -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mlittle-endian

-include Debug/main.d
Debug/main.o:Core/Src/main.c
	C:/ARMToolchain/bin/arm-none-eabi-gcc -c -DDEBUG -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Core/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Device/ST/STM32F4xx/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F Core/Src/main.c -MD -MF Debug/main.d -fno-diagnostics-show-caret -o Debug/main.o -Os -g3 -ffunction-sections -fdata-sections -Wall -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mlittle-endian

-include Debug/stm32f4xx_hal_msp.d
Debug/stm32f4xx_hal_msp.o:Core/Src/stm32f4xx_hal_msp.c
	C:/ARMToolchain/bin/arm-none-eabi-gcc -c -DDEBUG -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Core/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Device/ST/STM32F4xx/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F Core/Src/stm32f4xx_hal_msp.c -MD -MF Debug/stm32f4xx_hal_msp.d -fno-diagnostics-show-caret -o Debug/stm32f4xx_hal_msp.o -Os -g3 -ffunction-sections -fdata-sections -Wall -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mlittle-endian

-include Debug/stm32f4xx_hal_timebase_tim.d
Debug/stm32f4xx_hal_timebase_tim.o:Core/Src/stm32f4xx_hal_timebase_tim.c
	C:/ARMToolchain/bin/arm-none-eabi-gcc -c -DDEBUG -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Core/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Device/ST/STM32F4xx/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F Core/Src/stm32f4xx_hal_timebase_tim.c -MD -MF Debug/stm32f4xx_hal_timebase_tim.d -fno-diagnostics-show-caret -o Debug/stm32f4xx_hal_timebase_tim.o -Os -g3 -ffunction-sections -fdata-sections -Wall -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mlittle-endian

-include Debug/stm32f4xx_it.d
Debug/stm32f4xx_it.o:Core/Src/stm32f4xx_it.c
	C:/ARMToolchain/bin/arm-none-eabi-gcc -c -DDEBUG -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Core/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Device/ST/STM32F4xx/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F Core/Src/stm32f4xx_it.c -MD -MF Debug/stm32f4xx_it.d -fno-diagnostics-show-caret -o Debug/stm32f4xx_it.o -Os -g3 -ffunction-sections -fdata-sections -Wall -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mlittle-endian

-include Debug/syscalls.d
Debug/syscalls.o:Core/Src/syscalls.c
	C:/ARMToolchain/bin/arm-none-eabi-gcc -c -DDEBUG -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Core/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Device/ST/STM32F4xx/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F Core/Src/syscalls.c -MD -MF Debug/syscalls.d -fno-diagnostics-show-caret -o Debug/syscalls.o -Os -g3 -ffunction-sections -fdata-sections -Wall -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mlittle-endian

-include Debug/sysmem.d
Debug/sysmem.o:Core/Src/sysmem.c
	C:/ARMToolchain/bin/arm-none-eabi-gcc -c -DDEBUG -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Core/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Device/ST/STM32F4xx/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F Core/Src/sysmem.c -MD -MF Debug/sysmem.d -fno-diagnostics-show-caret -o Debug/sysmem.o -Os -g3 -ffunction-sections -fdata-sections -Wall -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mlittle-endian

-include Debug/system_stm32f4xx.d
Debug/system_stm32f4xx.o:Core/Src/system_stm32f4xx.c
	C:/ARMToolchain/bin/arm-none-eabi-gcc -c -DDEBUG -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Core/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Device/ST/STM32F4xx/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F Core/Src/system_stm32f4xx.c -MD -MF Debug/system_stm32f4xx.d -fno-diagnostics-show-caret -o Debug/system_stm32f4xx.o -Os -g3 -ffunction-sections -fdata-sections -Wall -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mlittle-endian

-include Debug/startup_stm32f411retx.d
Debug/startup_stm32f411retx.o:Core/Startup/startup_stm32f411retx.s
	C:/ARMToolchain/bin/arm-none-eabi-gcc -c -DDEBUG -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Core/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Device/ST/STM32F4xx/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F Core/Startup/startup_stm32f411retx.s -o Debug/startup_stm32f411retx.o -g3 -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mlittle-endian

-include Debug/stm32f4xx_hal.d
Debug/stm32f4xx_hal.o:Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c
	C:/ARMToolchain/bin/arm-none-eabi-gcc -c -DDEBUG -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Core/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Device/ST/STM32F4xx/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c -MD -MF Debug/stm32f4xx_hal.d -fno-diagnostics-show-caret -o Debug/stm32f4xx_hal.o -Os -g3 -ffunction-sections -fdata-sections -Wall -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mlittle-endian

-include Debug/stm32f4xx_hal_cortex.d
Debug/stm32f4xx_hal_cortex.o:Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c
	C:/ARMToolchain/bin/arm-none-eabi-gcc -c -DDEBUG -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Core/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Device/ST/STM32F4xx/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c -MD -MF Debug/stm32f4xx_hal_cortex.d -fno-diagnostics-show-caret -o Debug/stm32f4xx_hal_cortex.o -Os -g3 -ffunction-sections -fdata-sections -Wall -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mlittle-endian

-include Debug/stm32f4xx_hal_dma.d
Debug/stm32f4xx_hal_dma.o:Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c
	C:/ARMToolchain/bin/arm-none-eabi-gcc -c -DDEBUG -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Core/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Device/ST/STM32F4xx/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c -MD -MF Debug/stm32f4xx_hal_dma.d -fno-diagnostics-show-caret -o Debug/stm32f4xx_hal_dma.o -Os -g3 -ffunction-sections -fdata-sections -Wall -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mlittle-endian

-include Debug/stm32f4xx_hal_dma_ex.d
Debug/stm32f4xx_hal_dma_ex.o:Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c
	C:/ARMToolchain/bin/arm-none-eabi-gcc -c -DDEBUG -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Core/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Device/ST/STM32F4xx/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c -MD -MF Debug/stm32f4xx_hal_dma_ex.d -fno-diagnostics-show-caret -o Debug/stm32f4xx_hal_dma_ex.o -Os -g3 -ffunction-sections -fdata-sections -Wall -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mlittle-endian

-include Debug/stm32f4xx_hal_exti.d
Debug/stm32f4xx_hal_exti.o:Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c
	C:/ARMToolchain/bin/arm-none-eabi-gcc -c -DDEBUG -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Core/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Device/ST/STM32F4xx/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c -MD -MF Debug/stm32f4xx_hal_exti.d -fno-diagnostics-show-caret -o Debug/stm32f4xx_hal_exti.o -Os -g3 -ffunction-sections -fdata-sections -Wall -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mlittle-endian

-include Debug/stm32f4xx_hal_flash.d
Debug/stm32f4xx_hal_flash.o:Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c
	C:/ARMToolchain/bin/arm-none-eabi-gcc -c -DDEBUG -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Core/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Device/ST/STM32F4xx/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c -MD -MF Debug/stm32f4xx_hal_flash.d -fno-diagnostics-show-caret -o Debug/stm32f4xx_hal_flash.o -Os -g3 -ffunction-sections -fdata-sections -Wall -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mlittle-endian

-include Debug/stm32f4xx_hal_flash_ex.d
Debug/stm32f4xx_hal_flash_ex.o:Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c
	C:/ARMToolchain/bin/arm-none-eabi-gcc -c -DDEBUG -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Core/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Device/ST/STM32F4xx/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c -MD -MF Debug/stm32f4xx_hal_flash_ex.d -fno-diagnostics-show-caret -o Debug/stm32f4xx_hal_flash_ex.o -Os -g3 -ffunction-sections -fdata-sections -Wall -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mlittle-endian

-include Debug/stm32f4xx_hal_flash_ramfunc.d
Debug/stm32f4xx_hal_flash_ramfunc.o:Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c
	C:/ARMToolchain/bin/arm-none-eabi-gcc -c -DDEBUG -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Core/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Device/ST/STM32F4xx/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c -MD -MF Debug/stm32f4xx_hal_flash_ramfunc.d -fno-diagnostics-show-caret -o Debug/stm32f4xx_hal_flash_ramfunc.o -Os -g3 -ffunction-sections -fdata-sections -Wall -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mlittle-endian

-include Debug/stm32f4xx_hal_gpio.d
Debug/stm32f4xx_hal_gpio.o:Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c
	C:/ARMToolchain/bin/arm-none-eabi-gcc -c -DDEBUG -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Core/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Device/ST/STM32F4xx/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c -MD -MF Debug/stm32f4xx_hal_gpio.d -fno-diagnostics-show-caret -o Debug/stm32f4xx_hal_gpio.o -Os -g3 -ffunction-sections -fdata-sections -Wall -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mlittle-endian

-include Debug/stm32f4xx_hal_pwr.d
Debug/stm32f4xx_hal_pwr.o:Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c
	C:/ARMToolchain/bin/arm-none-eabi-gcc -c -DDEBUG -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Core/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Device/ST/STM32F4xx/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c -MD -MF Debug/stm32f4xx_hal_pwr.d -fno-diagnostics-show-caret -o Debug/stm32f4xx_hal_pwr.o -Os -g3 -ffunction-sections -fdata-sections -Wall -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mlittle-endian

-include Debug/stm32f4xx_hal_pwr_ex.d
Debug/stm32f4xx_hal_pwr_ex.o:Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c
	C:/ARMToolchain/bin/arm-none-eabi-gcc -c -DDEBUG -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Core/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Device/ST/STM32F4xx/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c -MD -MF Debug/stm32f4xx_hal_pwr_ex.d -fno-diagnostics-show-caret -o Debug/stm32f4xx_hal_pwr_ex.o -Os -g3 -ffunction-sections -fdata-sections -Wall -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mlittle-endian

-include Debug/stm32f4xx_hal_rcc.d
Debug/stm32f4xx_hal_rcc.o:Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c
	C:/ARMToolchain/bin/arm-none-eabi-gcc -c -DDEBUG -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Core/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Device/ST/STM32F4xx/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c -MD -MF Debug/stm32f4xx_hal_rcc.d -fno-diagnostics-show-caret -o Debug/stm32f4xx_hal_rcc.o -Os -g3 -ffunction-sections -fdata-sections -Wall -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mlittle-endian

-include Debug/stm32f4xx_hal_rcc_ex.d
Debug/stm32f4xx_hal_rcc_ex.o:Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c
	C:/ARMToolchain/bin/arm-none-eabi-gcc -c -DDEBUG -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Core/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Device/ST/STM32F4xx/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c -MD -MF Debug/stm32f4xx_hal_rcc_ex.d -fno-diagnostics-show-caret -o Debug/stm32f4xx_hal_rcc_ex.o -Os -g3 -ffunction-sections -fdata-sections -Wall -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mlittle-endian

-include Debug/stm32f4xx_hal_tim.d
Debug/stm32f4xx_hal_tim.o:Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c
	C:/ARMToolchain/bin/arm-none-eabi-gcc -c -DDEBUG -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Core/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Device/ST/STM32F4xx/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c -MD -MF Debug/stm32f4xx_hal_tim.d -fno-diagnostics-show-caret -o Debug/stm32f4xx_hal_tim.o -Os -g3 -ffunction-sections -fdata-sections -Wall -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mlittle-endian

-include Debug/stm32f4xx_hal_tim_ex.d
Debug/stm32f4xx_hal_tim_ex.o:Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c
	C:/ARMToolchain/bin/arm-none-eabi-gcc -c -DDEBUG -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Core/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Device/ST/STM32F4xx/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c -MD -MF Debug/stm32f4xx_hal_tim_ex.d -fno-diagnostics-show-caret -o Debug/stm32f4xx_hal_tim_ex.o -Os -g3 -ffunction-sections -fdata-sections -Wall -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mlittle-endian

-include Debug/stm32f4xx_hal_uart.d
Debug/stm32f4xx_hal_uart.o:Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c
	C:/ARMToolchain/bin/arm-none-eabi-gcc -c -DDEBUG -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Core/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Device/ST/STM32F4xx/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c -MD -MF Debug/stm32f4xx_hal_uart.d -fno-diagnostics-show-caret -o Debug/stm32f4xx_hal_uart.o -Os -g3 -ffunction-sections -fdata-sections -Wall -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mlittle-endian

-include Debug/cmsis_os2.d
Debug/cmsis_os2.o:Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/cmsis_os2.c
	C:/ARMToolchain/bin/arm-none-eabi-gcc -c -DDEBUG -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Core/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Device/ST/STM32F4xx/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/cmsis_os2.c -MD -MF Debug/cmsis_os2.d -fno-diagnostics-show-caret -o Debug/cmsis_os2.o -Os -g3 -ffunction-sections -fdata-sections -Wall -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mlittle-endian

-include Debug/croutine.d
Debug/croutine.o:Middlewares/Third_Party/FreeRTOS/Source/croutine.c
	C:/ARMToolchain/bin/arm-none-eabi-gcc -c -DDEBUG -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Core/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Device/ST/STM32F4xx/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F Middlewares/Third_Party/FreeRTOS/Source/croutine.c -MD -MF Debug/croutine.d -fno-diagnostics-show-caret -o Debug/croutine.o -Os -g3 -ffunction-sections -fdata-sections -Wall -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mlittle-endian

-include Debug/event_groups.d
Debug/event_groups.o:Middlewares/Third_Party/FreeRTOS/Source/event_groups.c
	C:/ARMToolchain/bin/arm-none-eabi-gcc -c -DDEBUG -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Core/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Device/ST/STM32F4xx/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F Middlewares/Third_Party/FreeRTOS/Source/event_groups.c -MD -MF Debug/event_groups.d -fno-diagnostics-show-caret -o Debug/event_groups.o -Os -g3 -ffunction-sections -fdata-sections -Wall -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mlittle-endian

-include Debug/list.d
Debug/list.o:Middlewares/Third_Party/FreeRTOS/Source/list.c
	C:/ARMToolchain/bin/arm-none-eabi-gcc -c -DDEBUG -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Core/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Device/ST/STM32F4xx/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F Middlewares/Third_Party/FreeRTOS/Source/list.c -MD -MF Debug/list.d -fno-diagnostics-show-caret -o Debug/list.o -Os -g3 -ffunction-sections -fdata-sections -Wall -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mlittle-endian

-include Debug/port.d
Debug/port.o:Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/port.c
	C:/ARMToolchain/bin/arm-none-eabi-gcc -c -DDEBUG -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Core/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Device/ST/STM32F4xx/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/port.c -MD -MF Debug/port.d -fno-diagnostics-show-caret -o Debug/port.o -Os -g3 -ffunction-sections -fdata-sections -Wall -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mlittle-endian

-include Debug/heap_4.d
Debug/heap_4.o:Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c
	C:/ARMToolchain/bin/arm-none-eabi-gcc -c -DDEBUG -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Core/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Device/ST/STM32F4xx/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c -MD -MF Debug/heap_4.d -fno-diagnostics-show-caret -o Debug/heap_4.o -Os -g3 -ffunction-sections -fdata-sections -Wall -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mlittle-endian

-include Debug/queue.d
Debug/queue.o:Middlewares/Third_Party/FreeRTOS/Source/queue.c
	C:/ARMToolchain/bin/arm-none-eabi-gcc -c -DDEBUG -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Core/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Device/ST/STM32F4xx/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F Middlewares/Third_Party/FreeRTOS/Source/queue.c -MD -MF Debug/queue.d -fno-diagnostics-show-caret -o Debug/queue.o -Os -g3 -ffunction-sections -fdata-sections -Wall -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mlittle-endian

-include Debug/stream_buffer.d
Debug/stream_buffer.o:Middlewares/Third_Party/FreeRTOS/Source/stream_buffer.c
	C:/ARMToolchain/bin/arm-none-eabi-gcc -c -DDEBUG -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Core/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Device/ST/STM32F4xx/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F Middlewares/Third_Party/FreeRTOS/Source/stream_buffer.c -MD -MF Debug/stream_buffer.d -fno-diagnostics-show-caret -o Debug/stream_buffer.o -Os -g3 -ffunction-sections -fdata-sections -Wall -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mlittle-endian

-include Debug/tasks.d
Debug/tasks.o:Middlewares/Third_Party/FreeRTOS/Source/tasks.c
	C:/ARMToolchain/bin/arm-none-eabi-gcc -c -DDEBUG -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Core/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Device/ST/STM32F4xx/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F Middlewares/Third_Party/FreeRTOS/Source/tasks.c -MD -MF Debug/tasks.d -fno-diagnostics-show-caret -o Debug/tasks.o -Os -g3 -ffunction-sections -fdata-sections -Wall -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mlittle-endian

-include Debug/timers.d
Debug/timers.o:Middlewares/Third_Party/FreeRTOS/Source/timers.c
	C:/ARMToolchain/bin/arm-none-eabi-gcc -c -DDEBUG -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Core/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Device/ST/STM32F4xx/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Drivers/CMSIS/Include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/include -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -IC:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F Middlewares/Third_Party/FreeRTOS/Source/timers.c -MD -MF Debug/timers.d -fno-diagnostics-show-caret -o Debug/timers.o -Os -g3 -ffunction-sections -fdata-sections -Wall -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mlittle-endian

Debug/stm32.elf:\
  Debug/freertos.o\
  Debug/LCD.o\
  Debug/main.o\
  Debug/stm32f4xx_hal_msp.o\
  Debug/stm32f4xx_hal_timebase_tim.o\
  Debug/stm32f4xx_it.o\
  Debug/syscalls.o\
  Debug/sysmem.o\
  Debug/system_stm32f4xx.o\
  Debug/startup_stm32f411retx.o\
  Debug/stm32f4xx_hal.o\
  Debug/stm32f4xx_hal_cortex.o\
  Debug/stm32f4xx_hal_dma.o\
  Debug/stm32f4xx_hal_dma_ex.o\
  Debug/stm32f4xx_hal_exti.o\
  Debug/stm32f4xx_hal_flash.o\
  Debug/stm32f4xx_hal_flash_ex.o\
  Debug/stm32f4xx_hal_flash_ramfunc.o\
  Debug/stm32f4xx_hal_gpio.o\
  Debug/stm32f4xx_hal_pwr.o\
  Debug/stm32f4xx_hal_pwr_ex.o\
  Debug/stm32f4xx_hal_rcc.o\
  Debug/stm32f4xx_hal_rcc_ex.o\
  Debug/stm32f4xx_hal_tim.o\
  Debug/stm32f4xx_hal_tim_ex.o\
  Debug/stm32f4xx_hal_uart.o\
  Debug/cmsis_os2.o\
  Debug/croutine.o\
  Debug/event_groups.o\
  Debug/list.o\
  Debug/port.o\
  Debug/heap_4.o\
  Debug/queue.o\
  Debug/stream_buffer.o\
  Debug/tasks.o\
  Debug/timers.o\
  C:/Users/gaming/STM32CubeIDE/workspace_1.5.0/stm32//STM32F411RETX_FLASH.ld
	C:/ARMToolchain/bin/arm-none-eabi-gcc -Wl,--gc-sections -lm --specs=nosys.specs --specs=nano.specs -T STM32F411RETX_FLASH.ld Debug/freertos.o Debug/LCD.o Debug/main.o Debug/stm32f4xx_hal_msp.o Debug/stm32f4xx_hal_timebase_tim.o Debug/stm32f4xx_it.o Debug/syscalls.o Debug/sysmem.o Debug/system_stm32f4xx.o Debug/startup_stm32f411retx.o Debug/stm32f4xx_hal.o Debug/stm32f4xx_hal_cortex.o Debug/stm32f4xx_hal_dma.o Debug/stm32f4xx_hal_dma_ex.o Debug/stm32f4xx_hal_exti.o Debug/stm32f4xx_hal_flash.o Debug/stm32f4xx_hal_flash_ex.o Debug/stm32f4xx_hal_flash_ramfunc.o Debug/stm32f4xx_hal_gpio.o Debug/stm32f4xx_hal_pwr.o Debug/stm32f4xx_hal_pwr_ex.o Debug/stm32f4xx_hal_rcc.o Debug/stm32f4xx_hal_rcc_ex.o Debug/stm32f4xx_hal_tim.o Debug/stm32f4xx_hal_tim_ex.o Debug/stm32f4xx_hal_uart.o Debug/cmsis_os2.o Debug/croutine.o Debug/event_groups.o Debug/list.o Debug/port.o Debug/heap_4.o Debug/queue.o Debug/stream_buffer.o Debug/tasks.o Debug/timers.o -o Debug/stm32.elf -Xlinker -Map=Debug/stm32.map -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mlittle-endian
	C:/ARMToolchain/bin/arm-none-eabi-objcopy Debug/stm32.elf Debug/stm32.hex -Oihex